spring.application.name=carhubd

server.port=8094
spring.datasource.username=root
spring.datasource.password=miku123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://54.209.249.219:3306/usuario


#opcional: (mostrar en consola las consultas)
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

