spring.application.name=notificaciones
server.port=8089

spring.datasource.url=jdbc:mysql://db-carhub.csg7nx8cqjdc.us-east-1.rds.amazonaws.com:3306/carhub_notificaciones
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=adminadmin
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update