server:
    port: 8080

spring:
    application:
        name: ms-bff
    cloud:
        gateway:
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "http:localhost//:4200"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                        allowedHeaders: "*"
            routes:
                - id: ms-vehiculos
                  uri: http://localhost:8095
                  predicates:
                    - Path=/api/v2/vehiculos**