server:
    port: 8080

spring:
    application:
        name: ms-bff
    cloud:
        gateway:
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "http:localhost//:4200"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                        allowedHeaders: "*"
            routes:
                #usuarios
                - id: ms-usuarios
                  uri: http://localhost:8085
                  predicates:
                    - Path=/api/v2/usuarios/**

                #login
                - id: ms-login
                  uri: http://localhost:8094
                  predicates:
                    - Path=/api/v2/auth/**
                    - Path=/api/v2/login/**