spring.application.name=register

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Empanadas
spring.datasource.password=omatsurimambo
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#creacion de tablas automaticamente
spring.jpa.hibernate.ddl-auto=update