spring.application.name=usuarios

spring.datasource.url=db-carhub.csg7nx8cqjdc.us-east-1.rds.amazonaws.com
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=adminadmin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#creacion de tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

