spring.application.name=ms-ventas
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/carhub_ventas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html